# Generated by Django 4.2.16 on 2024-11-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('index', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=100, null=True)),
                ('subject1', models.CharField(max_length=50)),
                ('subject2', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('date', models.CharField(max_length=200)),
                ('etc', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ARTICLE',
            },
        ),
    ]
