
# Generated by Django 4.2.16 on 2024-11-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberID', models.CharField(max_length=15, verbose_name='아이디')),
                ('password', models.CharField(max_length=15, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=30, verbose_name='사용자명')),
                ('email', models.EmailField(max_length=30, verbose_name='이메일')),
                ('subject1', models.CharField(max_length=30, verbose_name='주제1')),
                ('subject2', models.CharField(max_length=30, verbose_name='주제2')),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='회원가입일자 ')),
            ],
            options={
                'db_table': 'MEMBER',
            },
        ),
    ]
