# Generated by Django 4.2.16 on 2024-11-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='subject1',
            field=models.CharField(max_length=30, null=True, verbose_name='주제1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='subject2',
            field=models.CharField(max_length=30, null=True, verbose_name='주제2'),
        ),
    ]
